package lab7p2_joselobo;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        File fichero = new File("./Datos.dt");
        if (fichero.exists()) {
            todo = new Total();
        } else {
            FileInputStream entrada = null;
            ObjectInputStream objeto = null;
            try {
                entrada = new FileInputStream(fichero);
                objeto = new ObjectInputStream(entrada);
                todo = (Total) objeto.readObject();
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                objeto.close();
                entrada.close();
            } catch (IOException ex) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_popup_Carpeta = new javax.swing.JPopupMenu();
        Crear_Carpeta = new javax.swing.JMenuItem();
        Crear_Archivo = new javax.swing.JMenuItem();
        Eliminar_Carpeta = new javax.swing.JMenuItem();
        Decargar_Carpeta = new javax.swing.JMenuItem();
        menu_popup_Archivo = new javax.swing.JPopupMenu();
        Eliminar_Archivo = new javax.swing.JMenuItem();
        Descargar_Archivo = new javax.swing.JMenuItem();
        menu_popup_Root = new javax.swing.JPopupMenu();
        Crear_CarpetaRoot = new javax.swing.JMenuItem();
        Crear_ArchivoRoot = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        Decargar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_Principal = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTree = new javax.swing.JTree();
        lb_Administracion = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JL_Descargas = new javax.swing.JList<>();
        lb_RecienDescargado = new javax.swing.JLabel();
        JP_Archivos = new javax.swing.JProgressBar();
        JP_Carpeta = new javax.swing.JProgressBar();
        lb_Carpeta = new javax.swing.JLabel();
        lb_Archivos = new javax.swing.JLabel();

        Crear_Carpeta.setText("Crear Carpeta");
        Crear_Carpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_CarpetaActionPerformed(evt);
            }
        });
        menu_popup_Carpeta.add(Crear_Carpeta);

        Crear_Archivo.setText("Crear Archivo");
        menu_popup_Carpeta.add(Crear_Archivo);

        Eliminar_Carpeta.setText("Eliminar");
        menu_popup_Carpeta.add(Eliminar_Carpeta);

        Decargar_Carpeta.setText("Descargar Carpeta");
        menu_popup_Carpeta.add(Decargar_Carpeta);

        Eliminar_Archivo.setText("Eliminar");
        menu_popup_Archivo.add(Eliminar_Archivo);

        Descargar_Archivo.setText("jMenuItem1");
        menu_popup_Archivo.add(Descargar_Archivo);

        Crear_CarpetaRoot.setText("Crear Carpeta");
        menu_popup_Root.add(Crear_CarpetaRoot);

        Crear_ArchivoRoot.setText("Crear Archivo");
        menu_popup_Root.add(Crear_ArchivoRoot);

        Eliminar.setText("Eliminar");
        menu_popup_Root.add(Eliminar);

        Decargar.setText("Descargar Carpeta");
        menu_popup_Root.add(Decargar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Google Drive");

        JL_Principal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JL_Principal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Mi Unidad", "Destacados", "Papeleria" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JL_Principal.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                JL_PrincipalValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(JL_Principal);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        JTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        JTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTreeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTree);

        lb_Administracion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_Administracion.setText("Administracion");

        jScrollPane3.setViewportView(JL_Descargas);

        lb_RecienDescargado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_RecienDescargado.setText("Recien Descargado");

        JP_Archivos.setStringPainted(true);

        JP_Carpeta.setStringPainted(true);

        lb_Carpeta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Carpeta.setText("Carpeta");

        lb_Archivos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Archivos.setText("Archivos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JP_Archivos, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lb_RecienDescargado)
                                    .addGap(64, 64, 64)))
                            .addComponent(JP_Carpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_Carpeta)
                            .addComponent(lb_Archivos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(lb_Administracion)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(lb_Administracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_Carpeta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JP_Carpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(lb_Archivos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JP_Archivos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_RecienDescargado)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTreeMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = JTree.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            JTree.setSelectionRow(row);
            Object v1
                    = JTree.getSelectionPath().
                            getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Carpeta) {
                carpeta_seleccionada
                        = (Carpeta) nodo_seleccionado.
                                getUserObject();
                menu_popup_Carpeta.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            } else if (nodo_seleccionado.getUserObject() instanceof Archivo) {
                menu_popup_Archivo.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            } else {

            }
        }
    }//GEN-LAST:event_JTreeMouseClicked

    private void JL_PrincipalValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_JL_PrincipalValueChanged
        // TODO add your handling code here:
        if (JL_Principal.getSelectedIndex() == 0) {
            JTree.setModel(todo.getMiUnidad().getModel());
        }
        if (JL_Principal.getSelectedIndex() == 1) {
            JTree.setModel(todo.getDestacados().getModel());
        }
        if (JL_Principal.getSelectedIndex() == 2) {
            JTree.setModel(todo.getPapeleria().getModel());
        }
        DefaultTreeModel T = (DefaultTreeModel) JTree.getModel();
        T.reload();
    }//GEN-LAST:event_JL_PrincipalValueChanged

    private void Crear_CarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_CarpetaActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel Modelo = (DefaultTreeModel) JTree.getModel();
        nodo_seleccionado.getUserObject();
        DefaultMutableTreeNode t = new DefaultMutableTreeNode(Modelo);
        String nombre = JOptionPane.showInputDialog(this, "Ingrese el Nombre", "Nombre", -1);

    }//GEN-LAST:event_Crear_CarpetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public String GenerarAleatorio(int numero) {
        String temp = "";
        for (int i = 0; i < numero; i++) {
            int letra_numero = (int) (Math.random() * 1);
            if (letra_numero == 1) {
                //letra minusculas
                temp += (char) ((int) (Math.random() * 25) + 97);
            } else {
                //numero
                temp += (char) ((int) (Math.random() * 9) + 48);
            }
        }
        return temp;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Crear_Archivo;
    private javax.swing.JMenuItem Crear_ArchivoRoot;
    private javax.swing.JMenuItem Crear_Carpeta;
    private javax.swing.JMenuItem Crear_CarpetaRoot;
    private javax.swing.JMenuItem Decargar;
    private javax.swing.JMenuItem Decargar_Carpeta;
    private javax.swing.JMenuItem Descargar_Archivo;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Eliminar_Archivo;
    private javax.swing.JMenuItem Eliminar_Carpeta;
    private javax.swing.JList<String> JL_Descargas;
    private javax.swing.JList<String> JL_Principal;
    private javax.swing.JProgressBar JP_Archivos;
    private javax.swing.JProgressBar JP_Carpeta;
    private javax.swing.JTree JTree;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_Administracion;
    private javax.swing.JLabel lb_Archivos;
    private javax.swing.JLabel lb_Carpeta;
    private javax.swing.JLabel lb_RecienDescargado;
    private javax.swing.JPopupMenu menu_popup_Archivo;
    private javax.swing.JPopupMenu menu_popup_Carpeta;
    private javax.swing.JPopupMenu menu_popup_Root;
    // End of variables declaration//GEN-END:variables

    //Mis Variables
    DefaultMutableTreeNode nodo_seleccionado;
    Carpeta carpeta_seleccionada;
    Archivo archivo_seleccionada;
    Total todo;

}
